# Generated by Django 2.2.5 on 2019-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=5, verbose_name='Matricula :')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF:')),
                ('rg', models.CharField(max_length=7, verbose_name='RG:')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome:')),
                ('nomeGuerra', models.CharField(max_length=40, verbose_name='Nome de guerra: ')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço:')),
                ('complemento', models.CharField(max_length=150, verbose_name='Complemento do endereço:')),
                ('bairro', models.CharField(max_length=40, verbose_name='Bairro:')),
                ('cidade', models.CharField(max_length=40, verbose_name='Cidade:')),
                ('uf', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=2, verbose_name='UF:')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento:')),
                ('telefone', models.CharField(blank=True, max_length=12, verbose_name='Telefone:')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('dataAdmissao', models.DateField(verbose_name='Data de admissão:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(blank=True, choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=7, verbose_name='Status:')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['id', 'cpf', 'rg', 'matricula', 'nome', 'dataAdmissao', 'status'],
            },
        ),
    ]
