# Generated by Django 2.2.5 on 2019-10-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone:'),
        ),
    ]
