# Generated by Django 2.2.5 on 2019-11-04 00:00

from django.db import migrations, models
import funcionarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20191025_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, validators=[funcionarios.models.validar_cpf], verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(max_length=14, verbose_name='RG:'),
        ),
    ]
