# Generated by Django 2.2.5 on 2019-11-06 01:20

from django.db import migrations, models
import funcionarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20191103_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[funcionarios.models.validar_telefone], verbose_name='Telefone:'),
        ),
    ]
