# Generated by Django 2.2.5 on 2019-10-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20191017_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['id', 'cpf', 'rg', 'nome', 'dataAdmissao', 'status'], 'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='matricula',
        ),
    ]
