# Generated by Django 2.2.5 on 2019-11-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(default=2019, max_length=4, verbose_name='Ano')),
                ('mes', models.CharField(default=11, max_length=2, verbose_name='Mês')),
                ('valor', models.DecimalField(decimal_places=2, default=89.9, max_digits=6)),
                ('status', models.CharField(choices=[('PAGO', 'PAGO'), ('PENDENTE', 'PENDENTE')], max_length=8, verbose_name='Status de pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
    ]
