# Generated by Django 2.2.5 on 2019-11-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalidade',
            name='cliente',
        ),
    ]
