# Generated by Django 2.2.5 on 2019-11-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20191103_2204'),
        ('mensalidades', '0002_remove_mensalidade_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
            preserve_default=False,
        ),
    ]
