# Generated by Django 2.2.5 on 2019-11-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('EQUIPAMENTOS', 'EQUIPAMENTOS'), ('ATENDIMENTO', 'ATENDIMENTO'), ('INSTRUTORES', 'INSTRUTORES'), ('AMBIENTE', 'AMBIENTE')], default=None, max_length=12)),
            ],
            options={
                'verbose_name': 'Critério',
                'verbose_name_plural': 'Critérios',
                'ordering': ['id', 'criterio'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_avaliado', models.BooleanField(default=False)),
                ('notaCriterio1', models.IntegerField(default=0, null=True)),
                ('notaCriterio2', models.IntegerField(default=0, null=True)),
                ('notaCriterio3', models.IntegerField(default=0, null=True)),
                ('notaCriterio4', models.IntegerField(default=0, null=True)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('avaliador', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('criterio1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='avaliacoes.Criterio')),
                ('criterio2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='avaliacoes.Criterio')),
                ('criterio3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='avaliacoes.Criterio')),
                ('criterio4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='avaliacoes.Criterio')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['is_avaliado', 'notaCriterio1', 'notaCriterio2', 'notaCriterio3', 'notaCriterio4', 'comentario', 'criterio1', 'criterio2', 'criterio3', 'criterio4', 'avaliador', 'created_at'],
            },
        ),
    ]
