# Generated by Django 2.2.5 on 2019-11-06 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('EQUIPAMENTOS', 'EQUIPAMENTOS'), ('ATENDIMENTO', 'ATENDIMENTO'), ('INSTRUTORES', 'INSTRUTORES'), ('AMBIENTE', 'AMBIENTE')], default=None, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_avaliado', models.BooleanField(default=False)),
                ('nota', models.IntegerField(default=0)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentario')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.Criterio')),
            ],
        ),
    ]
