# Generated by Django 2.2.5 on 2019-11-07 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_auto_20191106_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['is_avaliado', 'nota', 'comentario', 'criterio', 'avaliador', 'created_at'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='criterio',
            options={'ordering': ['id', 'criterio'], 'verbose_name': 'Critério', 'verbose_name_plural': 'Critérios'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
