# Generated by Django 2.2.5 on 2019-11-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0006_auto_20191107_2141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('criterio', 'avaliador'), name='a'),
        ),
    ]
