# Generated by Django 2.2.5 on 2019-09-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='pesoa',
            new_name='peso',
        ),
    ]
