# Generated by Django 2.2.5 on 2019-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190908_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='peso',
            field=models.FloatField(max_length=3),
        ),
    ]
