# Generated by Django 2.2.5 on 2019-11-04 00:00

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20191027_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[clientes.models.validar_cpf], verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=14, verbose_name='RG:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[clientes.models.validar_telefone], verbose_name='Telefone:'),
        ),
    ]
