# Generated by Django 2.2.5 on 2019-11-04 00:04

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20191103_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, validators=[clientes.models.validar_cpf], verbose_name='CPF:'),
        ),
    ]
