# Generated by Django 2.2.5 on 2019-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0002_auto_20191122_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='is_presente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
